### ISSUE TITLE
if elif

### ISSUE THREAD

**Issue by andrieshiemstra** [Koxiaet/gpp#1]
Hi i was just wondering about the reason for not supporting if / elif.. is there a principal behind that or just a todo?

**Comment by Kestrer** [comment]
It's just a todo. Implementing C-style `#if`s would require adding another parser that supports operator precedence and a subset of C syntax. Definitely doable, and I would accept a PR for it, but I'm probably not going to implement it myself since it's a fair amount of work 😅.

**Comment by andrieshiemstra** [comment]
thank you for clearing that up, for now i'm happy with what it does!
